name: Update Formula Fields
description: Update homepage, url, sha256, and version in-place

inputs:
  version:
    required: true
  repo:
    required: true
  token:
    required: true
  action_name:
    required: true

runs:
  using: "composite"
  steps:
  - run: |
      set -ouex pipefail

      FORMULA="Formula/$(basename "$REPO").rb"
      TARBALL="https://github.com/$REPO/archive/refs/tags/$VERSION.tar.gz"
      SHA=$(curl -sL "$TARBALL" | shasum -a 256 | cut -d' ' -f1)

      sed -i'' \
        -e "s|^  homepage \".*\"|  homepage \"https://github.com/$REPO\"|" \
        -e "s|^  url \".*\"|  url \"$TARBALL\"|" \
        -e "s|^  sha256 \".*\"|  sha256 \"$SHA\"|" \
        -e "s|^  version \".*\"|  version \"${VERSION#v}\"|" \
        "$FORMULA"

      git config user.name "github-actions"
      git config user.email "github-actions@users.noreply.github.com"
      git commit -am "github-actions: run $ACTION_NAME for $VERSION"
      git push
    shell: bash
    env:
      REPO: ${{ inputs.repo }}
      VERSION: ${{ inputs.version }}
      ACTION_NAME: ${{ inputs.action_name }}
