name: Update Formula Fields
description: Update homepage, url, sha256, and version in-place

inputs:
  version:
    required: true
  repo:
    required: true
  token:
    required: true
  action_name:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        FORMULA="Formula/$(basename "${{ inputs.repo }}").rb"
        VERSION="${{ inputs.version }}"
        TARBALL="https://github.com/${{ inputs.repo }}/archive/refs/tags/${VERSION}.tar.gz"
        SHA=$(curl -sL "$TARBALL" | shasum -a 256 | cut -d' ' -f1)

        sed -i'' \
          -e "s|^  homepage \".*\"|  homepage \"https://github.com/${{ inputs.repo }}\"|" \
          -e "s|^  url \".*\"|  url \"${TARBALL}\"|" \
          -e "s|^  sha256 \".*\"|  sha256 \"${SHA}\"|" \
          -e "s|^  version \".*\"|  version \"${VERSION#v}\"|" \
          "$FORMULA"

        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git commit -am "github-actions: run ${{ inputs.action_name }} for ${VERSION}"
        git push
    shell: bash
