name: Publish to Tap
description: Copy and PR updated formula to homebrew-tap repo

inputs:
  token:
    required: true
  repo:
    required: true
  version:
    required: true
  repo_owner:
    required: true
  repo_name:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        FORMULA_FILE="Formula/${{ inputs.repo_name }}.rb"
        BRANCH="publish-${{ inputs.repo_name }}-${{ inputs.version }}"

        echo "Cloning tap repo..."
        git clone "https://x-access-token:${{ inputs.token }}@github.com/${{ inputs.repo_owner }}/homebrew-tap.git" tap
        cd tap

        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"

        git checkout -b "$BRANCH"

        echo "Fetching updated formula from source repo..."
        curl -sL "https://raw.githubusercontent.com/${{ inputs.repo }}/main/${FORMULA_FILE}" -o "${FORMULA_FILE}"

        git add "${FORMULA_FILE}"
        git commit -m "Mirror formula for ${{ inputs.repo_name }} ${inputs.version}"
        git push origin "$BRANCH"

        gh pr create \
          --title "Update formula: ${{ inputs.repo_name }} to ${{ inputs.version }}" \
          --body "This PR updates the Homebrew formula for ${{ inputs.repo_name }} to ${{ inputs.version }}." \
          --base main \
          --head "$BRANCH"
<<<<<<< HEAD
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.token }}
=======
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
>>>>>>> adelynnmckay
