name: Publish to Tap
description: Copy and PR updated formula to homebrew-tap repo

inputs:
  token:
    required: true
  repo:
    required: true
  version:
    required: true
  repo_owner:
    required: true
  repo_name:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        set -ouex pipefail

        FORMULA_FILE="Formula/$REPO_NAME.rb"
        BRANCH="publish-$REPO_NAME-$VERSION"

        echo "Cloning tap repo..."
        git clone "https://x-access-token:$GH_TOKEN@github.com/$REPO_OWNER/homebrew-tap.git" tap
        cd tap

        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"

        git checkout -b "$BRANCH"

        echo "Fetching updated formula from source repo..."
        mkdir -p Formula
        curl -sL "https://raw.githubusercontent.com/$REPO/main/${FORMULA_FILE}" -o "${FORMULA_FILE}"

        git add "${FORMULA_FILE}"
        git commit -m "Mirror formula for $REPO_NAME $VERSION"
        git push origin "$BRANCH"

        gh pr create \
          --title "Update formula: $REPO_NAME to $VERSION" \
          --body "This PR updates the Homebrew formula for $REPO_NAME to $VERSION." \
          --base main \
          --head "$BRANCH"
      shell: bash
      env:
        REPO_NAME: ${{ inputs.repo_name }}
        VERSION: ${{ inputs.version }}
        REPO_OWNER: ${{ inputs.repo_owner }}
        REPO: ${{ inputs.repo }}
        GH_TOKEN: ${{ inputs.token }}
