name: Create Release
description: Create a GitHub release with a new version
inputs:
  token:
    required: true
  version:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        git tag "$VERSION"
        git push origin "$VERSION"
        gh release create "$VERSION" --generate-notes
    shell: bash
    env:
      VERSION: ${{ inputs.version }}
      GH_TOKEN: ${{ inputs.token }}
